Generate minimal number of moves.
NatalijaGucevska/CodeU_6 pull request #2
Opened 2017-07-26 12:22 UTC by NatalijaGucevska

Here is the minimal moves algorithm that we discussed yesterday. It doesn't use copy of the `initialOrder` anymore and keeps inverse mapping only for misplaces car and the empty spot.

2017-07-26 12:51 UTC, arpita-biswas requested changes
The algorithm seems to perfectly find minimal number of moves. I have added few comments. Once everyone finishes reviewing this code, we can work on the test cases. :) Good job.

2017-07-26 12:51 UTC, arpita-biswas commented on Parking.java
> +		while (misplacedElementIndexMap.size() > 1 && !misplacedElementIndexMap.isEmpty()) {
!misplacedElementIndexMap.isEmpty() check is not required.

2017-07-26 12:51 UTC, arpita-biswas commented on Parking.java
> +			misplacedElementIndexMap.remove(0);
This step can be deleted. In line 54, misplacedElementIndexMap.put(0, currentPos) would take care of updating the value corresponding to 0. Hence, we can remove line 46.

2017-07-26 12:51 UTC, arpita-biswas commented on Parking.java
>  	public List<Move> getReorderMoves(List<Integer> initialOrder, List<Integer> targetOrder) {
The implementation is correct :) 
We can add few lines as a documentation for the method  getReorderMoves().

2017-07-26 13:49 UTC, nmeabed reviewed
I don't have much to add to Arpita's requested changes, 
Great job :) 
After all approve we can start working on the tests and try to replace the lists with arrays

2017-07-26 15:44 UTC, mirunamd commented
These changes look fine for me. The code is pretty much clear. Well done!

2017-07-26 15:45 UTC, mirunamd reviewed
These changes look fine for me. The code is clear. Well done!

2017-07-26 19:09 UTC, koska18 commented on Parking.java
> +			int emptySpot = misplacedElementIndexMap.get(0);
We can consider adding a field in this class:
`private final static int EMPTY_SPOT = 0`
and replace all zeros with this constant

2017-07-26 19:13 UTC, koska18 commented on Parking.java
> +	private Map<Integer, Integer> elementMapPosition(List<Integer> initialOrder, List<Integer> targetOrder) {
I know it's not important but name of this method bothers me a bit. For me one of good choices for the name would be `getMisplacedElementIndexMap` (because of returned value in line 39)  but that's only suggestion

2017-07-26 19:14 UTC, koska18 commented on Parking.java
> +			int emptySpot = misplacedElementIndexMap.get(0);
but then we should change variable name to `emptySpotPosition` or something. As I said, it's not a must.

2017-07-27 07:21 UTC, NatalijaGucevska commented on Parking.java
> +			misplacedElementIndexMap.remove(0);
I consider this remove as necessary since if we enter the condition on line 47, later on line 48 It wouldn't be that easy to find a random element using `iterator().next()` if 0 is present. We will have to add additional condition that will check that we are not having the position of the empty spot again...

2017-07-27 07:22 UTC, NatalijaGucevska commented on Parking.java
>  	public List<Move> getReorderMoves(List<Integer> initialOrder, List<Integer> targetOrder) {
Actually this branch contains only the changes. The documentation remains unchanged. (See pull request #1 )

2017-07-27 14:09 UTC, arpita-biswas approved these changes

2017-07-27 14:16 UTC, arpita-biswas reviewed
Shall we add a test to ensure minimal moves?

2017-07-27 14:17 UTC, mirunamd approved these changes

2017-07-27 14:17 UTC, mirunamd commented
Can you explain that more? Or how do you intend to do that?

2017-07-27 15:01 UTC, arpita-biswas commented
@mirunamd 
We can take an example such as initial = [1, 2, 0, 3] and target = [3, 1, 2, 0], and show that the number of moves is exactly 3 (since we already know its 3). This is not an exhaustive test over all instance but we can at least show that its works for an instance. 

However, in general, the minimum number of moves requires would be:  (n_0-1) + \sum_{i=1 to k}  [n_i + 1]  
where n_0 is the "permutation cycle" that includes the empty spot,  and n_i are the other permutation cycle. k represents the sum of permutation cycles excluding the one containing 0.

For example, if initial = [1,2,0,4,5,6,7,8] and target = [2,0,4,1,6,5,8,7], then there are three permutation cycles, 
(1,2,0,4), (5,6) and (7,8). So, n_0 = 4, n_1 = 2, and n_2 = 2. Thus, k=2.
Minimum number of moves required =  (n_0-1)+ n_1 + n_2 = (4-1) + 3 + 3 = 9. 

I understand implementing this test case would require a lot of effort, so we can just take an example where we know the number of moves and can test if the moves returned by our code attains the same.

2017-07-27 15:23 UTC, koska18 approved these changes

2017-07-27 15:47 UTC, nmeabed approved these changes

2017-07-27 15:49 UTC, merged